
# read distribution file as generated by patterndistribution.pl

sequence.location1<-"apical"
sequence.location2<-"basolateral"
sequence.folder<-"06_distributions"
domain<-"in"

#apical.patterns_on_apical.sequences.in.distribution.tsv
f.apical_1<-read.table(
	file=paste(sequence.folder,"/",sequence.location1,".patterns_on_apical.sequences.",domain,".distribution.tsv",sep=""),
	sep="\t", header=TRUE,
	na.strings="",
	row.names=1,
	fill=TRUE)
api_on_api<- as.matrix(f.apical_1)
num_of_rows<-nrow(api_on_api)
print(nrow(api_on_api))

#basoalteral.patterns_on_apical.sequences.in.distribution.tsv
f.apical_2<-read.table(
	file=paste(sequence.folder,"/",sequence.location2,".patterns_on_apical.sequences.",domain,".distribution.tsv",sep=""),
	sep="\t", header=TRUE,
	na.strings="",
	row.names=1,
	fill=TRUE)
baso_on_api<-as.matrix(f.apical_2)	
print(nrow(baso_on_api))

#apical.patterns_on_basolateral.sequences.in.distribution.tsv
f.basolateral_1<-read.table(
	file=paste(sequence.folder,"/",sequence.location1,".patterns_on_basolateral.sequences.",domain,".distribution.tsv",sep=""),
	sep="\t", header=TRUE,
	na.strings="",
	row.names=1,
	fill=TRUE)
api_on_baso<-as.matrix(f.basolateral_1)
print(nrow(api_on_baso))

#basoalteral.patterns_on_basolateral.sequences.in.distribution.tsv
f.basolateral_2<-read.table(
	file=paste(sequence.folder,"/",sequence.location2,".patterns_on_basolateral.sequences.",domain,".distribution.tsv",sep=""),
	sep="\t", header=TRUE,
	na.strings="",
	row.names=1,
	fill=TRUE)
baso_on_baso<-as.matrix(f.basolateral_2)
print(nrow(baso_on_baso))

table_top<-cbind(api_on_api,api_on_baso)
table_down<-cbind(baso_on_api,baso_on_baso)
table_comp<-rbind(table_top,table_down)

image(table_comp)
#  
# api_on_baso
# baso_on_baso
# baso_on_api
# 
# 
# rbind
# cbind
# image
# 
# if (any(is.na(f.apical))= {
# 	stop("There are NAs in the matrix.")
# }
# 
# #rownames(f.apical)<-f.apical[,1]
# #rownames(f.basolateral)<-f.basolateral[,1]
# #colnames(f.apical)<-f.apical[1,]
# #colnames(f.basolateral)<-f.basolateral[1,]
# 
# if(!all(rownames(f.apical)==rownames(f.basolateral))) {
# 	stop("The labeling of rows is not equal in both files.")
# }
# 
# #a<-f.apical[2:nrow(f.apical),2:ncol(f.apical)])
# f.api.baso<-cbind(f.apical,f.basolateral)
# f.api.baso[is.na(f.api.baso)]<-0
# f.api.baso[f.api.baso>0]<-1
# 
# f.api.baso.num<-as.matrix(f.api.baso)
# 
# f.api.header<-rep("api",ncol(f.apical))
# f.baso.header<-rep("baso",ncol(f.basolateral))
# f.api.baso.num.renamed<-f.api.baso.num
# colnames(f.api.baso.num.renamed)<-c(f.api.header,f.baso.header)
# #heatmap(f.api.baso.num.renamed)
# 
# f.api.baso.pca<-princomp(f.api.baso.num.renamed)
# biplot(f.api.baso.pca)
# 
# f<-function(dim.a,dim.b) {
# 	plot(t(f.api.baso.pca$scores)[27:61,c(dim.a,dim.b)],type="p",col="blue")
# 	points(t(f.api.baso.pca$scores)[1:26,c(dim.a,dim.b)],type="p",col="red")
# }
# o<-par(ask=TRUE)
# f(1,2)
# f(1,3)
# par(o)
# 

